apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    label-key: label-value
spec:
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80
