@startuml

cloud "Cloud" {

    file "Cloud Storage" as cloudstorage

}

node "Kubernetes Cluster" {

    file "Persistent Storage 10GB" as persistent

    node "Pod A" {
        file "Claim 2GB" as file1
    }

    node "Pod B" {
        file "Claim 2GB" as file2
    }

    node "Pod C" {
        file "Claim 2GB" as file3
    }

}

persistent -right-> cloudstorage
file1 --> persistent
file2 --> persistent
file3 --> persistent

@enduml
